boolean isStudent = true;
boolean hasPassedExam = false;
boolean isEqual = (15 == 15);
double price = 19.99;
double temperature = -2.5;
double result = 10.5 + 3.7;
double division = 10.0 / 3.0;
String name = "John";
String greeting = "Hello, World!";
String combined = name + "says " + greeting;
String empty = "";
String streak = "Godlike";
String pname = "ArteeSie";
String status = pname + " is beyond " + streak;